### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kyliel**
Update the readme.

### CODE REVIEW

**Comment by kyliel** [comment]
@zikalino could you please review the readme change? If ok, can you merge it? 
And it seems CI is triggered by this change. Why the change will triage CI build?

**Comment by zikalino** [comment]
@kyliel i will check it now and merge if everything's fine.
well, ci should be a bit smarter i guess...

**Comment by kyliel** [comment]
Please help take care the readme of preview_module. Thank you.

**Comment by zikalino** [comment]
ok, i will take care of that. i will also check why ci started failing here and make it green again...

**Pull request merged**
