### PR TITLE
[Feature] #58929 implement missing StorageProfile  parameters

### PR DESCRIPTION
**Pull request by Sispheor**
- [Python SDK reference]( https://docs.microsoft.com/en-us/python/api/azure-mgmt-rdbms/azure.mgmt.rdbms.postgresql.models.storageprofile?view=azure-python)
- [Ansible issue reference](https://github.com/ansible/ansible/issues/58929)

### CODE REVIEW

**Comment by MyronFanQiu** [comment]
@Sispheor Hello. Thanks for your contribution. Could you please send the PR to the [Ansible main repo](https://github.com/ansible/ansible) or to our [preview repo](https://github.com/Azure/azure_preview_modules)? This repo doesn't have the necessary integration test.

**Comment by Sispheor** [comment]
Done [here](https://github.com/Azure/azure_preview_modules/pull/291)

**Comment by MyronFanQiu** [comment]
@Sispheor Thanks! We can close this PR.

**Comment by Sispheor** [comment]
PR on Ansible project here: https://github.com/ansible/ansible/pull/64894

**Pull request closed without merging**
